# TODO(tetsuok): Re-enable once the existing issues are fixed.
MD001: false

# TODO(tetsuok): Re-enable once the existing issues are fixed.
MD013: false
  # Number of characters
  # line_length: 88
  # code_blocks: false

MD024:
  # Allow multiple headings with the same content
  siblings_only: true

# TODO(tetsuok): Re-enable once the existing issues are fixed.
MD033: false

# TODO(tetsuok): Re-enable once the existing issues are fixed.
MD036: false

# TODO(tetsuok): Re-enable once the existing issues are fixed.
MD046: false

ignores: ["explainaboard/third_party"]
