CREATE TABLE `task_ner` (
  `id` int(7) NOT NULL DEFAULT 0,
  `year` text NOT NULL,
  `conf` text NOT NULL,
  `task` text NOT NULL,
  `dataset` text NOT NULL,
  `metric` text NOT NULL,
  `model` text NOT NULL,
  `score` float NOT NULL,
  `title` text NOT NULL,
  `author` text NOT NULL,
  `url` text NOT NULL,
  `bib` text DEFAULT NULL,
  `single` longtext DEFAULT NULL,
  `databias` text DEFAULT NULL,
  `file` int(7) DEFAULT NULL,
  `sota` text DEFAULT NULL,
  `check_box` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
